### PR TITLE
AMBARI-26142: JDK17 support for Ambari-metrics

### PR DESCRIPTION
**Pull request by sandeepk318**
[AMBARI-26142] JDK17 support for Ambari-metrics

## What changes were proposed in this pull request?
upgrade maven-compiler-plugin to 3.5
maven-shade-plugin to 3.5.1
guava to 32.1.3-jre
maven-surefire-plugin  to 3.2.5
JDK to 17
API changes
tests cases modified

(Please fill in changes proposed in this fix)

## How was this patch tested?
TESTING is pending.

(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

Please review [Ambari Contributing Guide](https://cwiki.apache.org/confluence/display/AMBARI/How+to+Contribute) before opening a pull request.

### CODE REVIEW

**Comment by JiaLiangC** [comment]
@sandeep318kumar 
Due to being quite busy, we will handle the Ambari metrics-related PRs after completing the JDK, Spring, and other dependency upgrades on the Ambari side. Thank you for your contribution.

**Comment by JiaLiangC** [comment]
@sandeep318kumar It looks like three tests have failed. Could you please fix them?

**Comment by JiaLiangC** [comment]
@sandeep318kumar  It will be merged first, and the failed unit tests will be submitted in a separate PR.

**Review by JiaLiangC — APPROVED** [review]
LGTM

**Comment by sandeep318kumar** [comment]
@JiaLiangC Can I work on these test cases?

**Comment by JiaLiangC** [comment]
> @JiaLiangC Can I work on these test cases?

 @sandeep318kumar sorry for later reply, of course you can.

**Comment by vishalsuvagia** [comment]
Hi @JiaLiangC  we would need the JDK-17 support in Ambari metrics to enable helix-core fix https://github.com/apache/ambari-metrics/pull/173

**Pull request merged**
