### PR TITLE
AMBARI-25801: Make the version for Kafka,Hbase,Hadoop to be consistent with Ambari

### PR DESCRIPTION
**Pull request by timyuer**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

`mvn clean package -Dbuild-rpm -DskipTests`

e17080eec99277d04dcb50e6c285541

(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

Please review [Ambari Contributing Guide](https://cwiki.apache.org/confluence/display/AMBARI/How+to+Contribute) before opening a pull request.

### CODE REVIEW

**Comment by kevinw66** [comment]
Thanks @timyuer , but I can see this PR fixes more than one problems
1. Build fails due to rpm-maven-plugin upgrade
2. Deployment via Ambari fails
3. etc...
Can we split this PR into multiples?

**Comment by timyuer** [comment]
> Thanks @timyuer , but I can see this PR fixes more than one problems
> 
> 1. Build fails due to rpm-maven-plugin upgrade
> 2. Deployment via Ambari fails
> 3. etc...
>    Can we split this PR into multiples?

Sure.

**Comment by kevinw66** [comment]
Thanks @timyuer , looks we still have some dependency issues when using apache tarballs, can we use bigtop tarballs like this PR did? https://github.com/apache/bigtop/pull/1061

**Comment by timyuer** [comment]
> Thanks @timyuer , looks we still have some dependency issues when using apache tarballs, can we use bigtop tarballs like this PR did? [apache/bigtop#1061](https://github.com/apache/bigtop/pull/1061) Also, dependency `phoenix-hbase-compat-2.4.1` which deleted in this PR are still needed.

@kevinw66  
Thanks, I will submit another PR to deal with this problem, and the new PR will submit based on this PR to resolve file conflicts.

**Review by kevinw66 — APPROVED** [review]

**Pull request merged**
