### PR TITLE
AMBARI-25876: Bump version to 3.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by kevinw66**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

Please review [Ambari Contributing Guide](https://cwiki.apache.org/confluence/display/AMBARI/How+to+Contribute) before opening a pull request.

### CODE REVIEW

**Comment by sekikn** [comment]
+1, ensured that all version numbers in the code were updated and `mvn clean install -Dbuild-rpm` was successful on CentOS 7. Thanks @kevinw66!

```
$ rpm -qip ambari-metrics-assembly/target/rpm/ambari-metrics-collector/RPMS/x86_64/ambari-metrics-collector-3.0.0-SNAPSHOT.x86_64.rpm 
Name        : ambari-metrics-collector
Version     : 3.0.0
Release     : SNAPSHOT
...
```

**Comment by virajjasani** [comment]
I thought we wanted to go with 2.8.0? But 3.0.0 is fine too since we don't have any released version numbers closer to 3.0.0. 

Besides, Ambari 2.8.0 would be the first release with ambari-metrics getting released separately, correct?

**Comment by kevinw66** [comment]
> I thought we wanted to go with 2.8.0? But 3.0.0 is fine too since we don't have any released version numbers closer to 3.0.0.

@virajjasani Since we change the format of the version number, upgrade major version might be better I think.

> Besides, Ambari 2.8.0 would be the first release with ambari-metrics getting released separately, correct?

Yes.

**Comment by virajjasani** [comment]
Sounds good, thanks @kevinw66

**Pull request merged**
