### PR TITLE
AMBARI-25203 Updated jackson-databind to 2.9.8 and boucycastle libs to 1.61

### PR DESCRIPTION
**Pull request by lucasbak**
Backport: Ambari 25203 branch 2.7 (#2896) from benyoka

## How was this patch tested?

Only back port for now

Please review [Ambari Contributing Guide](https://cwiki.apache.org/confluence/display/AMBARI/How+to+Contribute) before opening a pull request.

### CODE REVIEW

**Comment by kevinw66** [comment]
Thanks @lucasbak ! Let's keep same title with original PR: https://github.com/apache/ambari/pull/2898
The title start with `AMBARI-` will auto link to JIRA issues, but only works on Ambari main repository now, I'll try to enable it for `ambari-metrics`, `ambari-infra`, `ambari-logsearch` also.

**Comment by kevinw66** [comment]
Thanks @lucasbak ! But the commit on branch-2.7 changes code on `ambari`, `ambari-infra`, `ambari-logsearch`, would you like to create PRs for them too?

**Comment by lucasbak** [comment]
Yes let's create PR for all subprojects including `ambari`, `ambari-infra` and `ambari-logsearch`

**Review by kevinw66 — APPROVED** [review]
+1 LGTM, thanks @lucasbak !

**Pull request merged**
